name: Push to GitLab

on:
  push:
    branches:
      - '*'

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitLab environment variables
      run: |
        echo "GITLAB_SSH_PRIVATE_KEY=${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "GITLAB_REPO_URL=git@git.rev9solutions.com:all-projects/pantsuit-professionals/frontend.git" >> $GITHUB_ENV

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$GITLAB_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Push to GitLab
      run: |
        # Extract the branch name from the GITHUB_REF variable
        BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        
        # Add the GitLab repository as a remote
        git remote add gitlab $GITLAB_REPO_URL
        
        # Push the code to the corresponding branch on GitLab
        git push gitlab $BRANCH_NAME
